# Generated by Django 6.0.4 on 2026-05-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_variant_type_variant_variant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='variant_name',
        ),
    ]
