# Generated by Django 6.0.4 on 2026-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_variant_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
