# Generated by Django 6.0.4 on 2026-05-25 10:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='download_1_nlzcjs', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
