# Generated by Django 6.0.4 on 2026-05-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not Requested', max_length=20),
        ),
    ]
