# Generated by Django 6.0.4 on 2026-07-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_coupon_order_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
