# Generated by Django 6.0.4 on 2026-07-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_orderaddress_orderitem_coupon_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stock_restored",
            field=models.BooleanField(default=False),
        ),
    ]
