# Generated by Django 6.0.4 on 2026-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderitem_stock_restored"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="refund_processed",
            field=models.BooleanField(default=False),
        ),
    ]
