# Generated by Django 6.0.4 on 2026-07-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderaddress_order_shipping_address"),
        ("orders", "0012_orderitem_refund_processed"),
    ]

    operations = []
